pipeline:
  build:
    image: node:${NODE_VERSION}
    commands:
      - [[ $NODE_VERSION == 4.4.2 ]] && npm install -g npm@3
      - npm install
      - npm test
matrix:
  NODE_VERSION:
    - 4.4.2
    - 5
