# local:
#     :url: https://staging.somewhere.com

# devnotprod:
#     :url: https://production.somewhere

environment: 'local'

submit: true

not_arrived_host: 'http://localhost:8080/not-arrived'

correct_mistakes_host: 'http://localhost:8080/correct-mistakes'

lost_stolen_host: 'http://localhost:8080/lost-stolen'

collection_host: 'http://localhost:8080/collection'

someone_host: 'http://localhost:8080/someone-else'

## Some handy debugging flags

# stop immediately on the first failing test
bail: false

# open a screenshot of the failure point
screenshot_on_fail: false
